backend:
  name: git-gateway
  branch: main

media_folder: "public/images/legos"
public_folder: "/images/legos"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "themes"
    label: "Themes"
    folder: "content/themes"
    create: true
    delete: true
    slug: "{{fields.title}}"
    identifier_field: "title"
    extension: "md"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Nom du theme", widget: "string", required: true }

  - name: "legos"
    label: "LEGO Sets"
    folder: "content/legos"
    create: true
    delete: true
    slug: "{{fields.name}}"
    identifier_field: "name"
    extension: "md"
    format: "frontmatter"
    media_folder: "/public/images/legos"
    public_folder: "/images/legos"
    sortable_fields: ["name", "date", "theme"]
    view_filters:
      - label: "Par theme"
        field: "theme"
    fields:
      - { name: "name", label: "Nom", widget: "string", required: true }
      - name: "theme"
        label: "Theme"
        widget: "relation"
        collection: "themes"
        value_field: "title"
        search_fields: ["title"]
        display_fields: ["title"]
        required: true
      - { name: "image", label: "Image", widget: "image", required: true }
      - { name: "date", label: "Date d'acquisition", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { name: "createdAt", label: "Date d'ajout", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, default: "{{now}}" }
      - { name: "body", label: "Notes", widget: "markdown", required: false }
